import {listNodes,saveNode,nodeOptions} from '@/lib/nodes';
import {env} from 'cloudflare:workers';
import {adminIdentity,database} from '@/lib/admin';
import {currentEvent,record,records} from '@/lib/operations';
import {orchestrate} from '@/lib/orchestrator';
const inside=(p:any,b:any)=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&p.lat>=b.south&&p.lat<=b.north&&p.lng>=b.west&&p.lng<=b.east;
async function context(params:any){const {eventId,resource}=await params;const event=await currentEvent();if(!event||event.id!==eventId)throw Error('Event not found.');const rows=await records(eventId);const location=rows.find((r:any)=>r.kind==='location')?.data??null;return {eventId,resource,rows,location}}
export async function GET(req:Request,{params}:any){try{const c=await context(params);if(c.resource!=='graph')return Response.json({error:'Not found'},{status:404});const cfg=env as unknown as Record<string,string>;return Response.json({location:c.location,nodes:await listNodes(c.eventId),nodeOptions,edges:c.rows.filter((r:any)=>r.kind==='edge').map((r:any)=>({id:r.id,...r.data})),routes:c.rows.find((r:any)=>r.kind==='live-routes')?.data.routes??[],updates:c.rows.filter((r:any)=>r.kind==='live-alert').map((r:any)=>r.data),socketUrl:cfg.EVENTFLOW_WS_URL??null},{headers:{'Cache-Control':'no-store'}})}catch(e){return Response.json({error:(e as Error).message},{status:503})}}
export async function POST(req:Request,{params}:any){if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid request.'},{status:403});try{const who=await adminIdentity();if(!['owner','admin'].includes(who.role))return Response.json({error:'Administrator access required.'},{status:403});const c=await context(params),b=await req.json() as any;const actor=String((who as any).userId??'administrator');
if(c.resource==='location'){const x=b.bounds;if(c.location?.locked)return Response.json({error:'Unlock the event location before saving another frame.'},{status:409});if(!x||![x.north,x.south,x.east,x.west,b.zoom,b.center?.lat,b.center?.lng].every(Number.isFinite)||x.north<=x.south||x.east<=x.west||x.north>90||x.south< -90||x.east>180||x.west< -180||b.zoom<0||!inside(b.center,x))throw Error('Invalid map bounds or zoom.');await record('location',c.eventId,{bounds:x,zoom:b.zoom,center:b.center,locked:true},actor);return Response.json({saved:true})}
if(c.resource==='unlock'){if(!c.location)throw Error('Save an event location first.');await record('location',c.eventId,{...c.location,locked:false},actor);return Response.json({saved:true})}
if(!c.location?.locked)throw Error('Save and lock the event location first.');
if(c.resource==='nodes')return Response.json(await saveNode(c.eventId,b));
if(c.resource==='edges'){const nodes=await listNodes(c.eventId);const from=nodes.find((n:any)=>n.node_id===b.from),to=nodes.find((n:any)=>n.node_id===b.to);if(!from||!to||from.node_id===to.node_id||!inside({lat:from.latitude,lng:from.longitude},c.location.bounds)||!inside({lat:to.latitude,lng:to.longitude},c.location.bounds))throw Error('Choose two different nodes within the event bounds.');const result:any=await orchestrate({action:'create_edge',eventId:c.eventId,from,to});if(!Array.isArray(result.geometry?.coordinates)||!Number.isFinite(result.distance))throw Error('The backend did not supply edge geometry and distance.');const id=await record('edge',c.eventId,{from:b.from,to:b.to,geometry:result.geometry,distance:result.distance},actor);return Response.json({id})}
return Response.json({error:'Not found'},{status:404})}catch(e){return Response.json({error:(e as Error).message},{status:503})}}
