'use client';
import {useEffect,useState} from 'react';
import {useEvent} from './event-live';
export default function CrowdInputs({place,onSaved}:{place:{lat:string;lon:string;display_name:string;node_id?:number}|null;onSaved:(row:any)=>void}){
 const {event,graph,canEdit,reload}=useEvent();const initial=graph.nodes.find((n:any)=>n.node_id===place?.node_id);const [row,setRow]=useState<any>(initial??null),[values,setValues]=useState({name:initial?.name??place?.display_name??'',type:initial?.type??'',external_id:initial?.external_id??'',capacity:initial?.capacity!=null?String(initial.capacity):'',status:initial?.status??graph.nodeOptions?.defaultStatus??''}),[saving,setSaving]=useState(false),[message,setMessage]=useState('');const options=graph.nodeOptions;
 useEffect(()=>{if(options)setValues(v=>({...v,status:v.status||options.defaultStatus}))},[options]);
 async function save(e:React.FormEvent){e.preventDefault();if(!place||!event||!options)return;const payload:any={name:values.name.trim(),type:values.type,latitude:Number(place.lat),longitude:Number(place.lon),capacity:Number(values.capacity),status:values.status};if(values.external_id.trim()||row?.external_id)payload.external_id=values.external_id.trim()||null;if(!payload.name||!options.types.includes(payload.type)||!options.statuses.includes(payload.status)||!Number.isInteger(payload.capacity)||payload.capacity<=0||![payload.latitude,payload.longitude].every(Number.isFinite)){setMessage('Enter a name, type, status and a positive whole-number capacity. Place a pin on the map.');return}const changed=row?Object.fromEntries(Object.entries(payload).filter(([key,value])=>value!==row[key])):payload;if(row&&!Object.keys(changed).length){setMessage('No changes to save.');return}setSaving(true);setMessage('');try{const r=await fetch(`/api/events/${encodeURIComponent(event.id)}/nodes${row?'/'+row.node_id:''}`,{method:row?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(changed)});const j:any=await r.json();if(!r.ok)throw Error(j.error);if(!Number.isInteger(j.node_id))throw Error('The backend did not return a node ID.');setRow(j);await reload();onSaved(j);setMessage('Node saved.')}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}
 return <section className="orchestrator"><h2>{row?'Edit node':'Node information'}</h2>{!canEdit?<a href="/admin">Administrator login to edit nodes</a>:!graph.location?.locked?<p>Save and lock the event area first.</p>:!place?<p>Tap the map to add a node.</p>:!options?<p>Loading allowed node values…</p>:<form className="event-form" onSubmit={save}><label>Name<input required maxLength={120} value={values.name} onChange={e=>setValues({...values,name:e.target.value})}/></label><label>Type<select required value={values.type} onChange={e=>setValues({...values,type:e.target.value})}><option value="" disabled>Choose type</option>{options.types.map((type:string)=><option key={type} value={type}>{type}</option>)}</select></label><label>Reference code (optional)<input maxLength={80} value={values.external_id} onChange={e=>setValues({...values,external_id:e.target.value})}/></label><label>People the place can hold<input required type="number" min="1" step="1" value={values.capacity} onChange={e=>setValues({...values,capacity:e.target.value})}/></label><label>Status<select required value={values.status} onChange={e=>setValues({...values,status:e.target.value})}><option value="" disabled>Choose status</option>{options.statuses.map((status:string)=><option key={status} value={status}>{status}</option>)}</select></label><dl className="node-coordinates"><dt>Latitude</dt><dd>{place.lat}</dd><dt>Longitude</dt><dd>{place.lon}</dd></dl><button className="primary" disabled={saving}>{saving?'Saving…':row?'Save changes':'Save information'}</button></form>}{message&&<p role="status">{message}</p>}</section>
}
