import {sqliteTable,text,integer,index,real} from 'drizzle-orm/sqlite-core';
export const administrators=sqliteTable('administrators',{userId:text('user_id').primaryKey(),email:text('email').notNull(),name:text('name').notNull(),organization:text('organization').notNull(),status:text('status').notNull().default('pending'),createdAt:text('created_at').notNull()});

export const credentialUsers=sqliteTable('credential_users',{userId:text('user_id').primaryKey(),userName:text('user_name').notNull(),role:text('role').notNull().default('administrator'),createdAt:text('created_at').notNull(),passwordHash:text('password_hash').notNull(),salt:text('salt').notNull(),iterations:integer('iterations').notNull(),status:text('status').notNull().default('pending'),isOwner:integer('is_owner').notNull().default(0)});
export const credentialSessions=sqliteTable('credential_sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>credentialUsers.userId),expiresAt:integer('expires_at').notNull()},t=>[index('idx_credential_sessions_user').on(t.userId)]);
export const authRateLimits=sqliteTable('auth_rate_limits',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),resetAt:integer('reset_at').notNull()});
export const venueInputs=sqliteTable('venue_inputs',{placeKey:text('place_key').primaryKey(),placeName:text('place_name').notNull(),expected:integer('expected').notNull(),current:integer('current').notNull(),capacity:integer('capacity').notNull(),updatedAt:text('updated_at').notNull(),updatedBy:text('updated_by').notNull()});
export const activeEvent=sqliteTable('active_event',{id:text('id').primaryKey(),data:text('data').notNull(),updatedAt:text('updated_at').notNull()});
export const operationRecords=sqliteTable('operation_records',{id:text('id').primaryKey(),eventId:text('event_id').notNull(),kind:text('kind').notNull(),parentId:text('parent_id'),data:text('data').notNull(),createdAt:text('created_at').notNull(),actor:text('actor').notNull()},t=>[index('idx_operations_event').on(t.eventId,t.createdAt)]);
export const eventKeys=sqliteTable('event_keys',{id:integer('id').primaryKey({autoIncrement:true}),routeId:text('route_id').notNull().unique()});
export const nodes=sqliteTable('nodes',{nodeId:integer('node_id').primaryKey({autoIncrement:true}),eventId:integer('event_id').notNull().references(()=>eventKeys.id),externalId:text('external_id',{length:80}),name:text('name',{length:120}).notNull(),type:text('type',{length:40}).notNull(),latitude:real('latitude').notNull(),longitude:real('longitude').notNull(),capacity:integer('capacity').notNull(),status:text('status',{length:30}).notNull(),createdAt:text('created_at').notNull()});
