/**
 * P1 ↔ P2 Contract
 *
 * Defines the structured communication between:
 *
 * P2 = AI / Strategy Intelligence
 * P1 = Deterministic Simulation Engine
 *
 * CORE RULE:
 * P2 proposes and interprets.
 * P1 validates, calculates, and simulates.
 *
 * P2 must never treat its own assumptions as authoritative
 * simulation results.
 */

// ---------------------------------------------------------
// Command Types
// ---------------------------------------------------------

export type P2CommandType =
  | "GET_EVENT_STATE"
  | "VALIDATE_STRATEGY"
  | "SIMULATE_STRATEGY";

// ---------------------------------------------------------
// P2 → P1 Command
// ---------------------------------------------------------

export interface P2ToP1Command {
  command_id: string;

  command_type: P2CommandType;

  event_id: string;

  /**
   * Strategy ID selected or generated by P2.
   *
   * Not required for GET_EVENT_STATE.
   */
  strategy_id?: string;

  /**
   * Candidate strategy parameters.
   *
   * P1 must validate these parameters before
   * using them in a simulation.
   */
  parameters?: Record<string, unknown>;

  /**
   * Optional reason explaining why P2 generated
   * the command.
   */
  reason?: string;
}

// ---------------------------------------------------------
// P1 Validation Result
// ---------------------------------------------------------

export interface P1ValidationResult {
  command_id: string;

  valid: boolean;

  errors: string[];

  warnings: string[];

  /**
   * P1 may return normalized parameters after validation.
   */
  normalized_parameters?: Record<string, unknown>;
}

// ---------------------------------------------------------
// P1 Simulation Result
// ---------------------------------------------------------

export interface P1SimulationResult {
  command_id: string;

  success: boolean;

  /**
   * Deterministic simulation output generated by P1.
   */
  results?: Record<string, unknown>;

  /**
   * Problems encountered during simulation.
   */
  errors?: string[];

  warnings?: string[];
}

// ---------------------------------------------------------
// P1 Event State
// ---------------------------------------------------------

export interface P1EventState {
  event_id: string;

  timestamp?: string;

  /**
   * These values are intentionally generic because
   * the exact P1 engine state structure is defined
   * by the existing engine implementation.
   */
  gates?: unknown[];

  exits?: unknown[];

  zones?: unknown[];

  routes?: unknown[];

  crowd_state?: unknown;

  risk_state?: unknown;

  capacity_state?: unknown;

  [key: string]: unknown;
}

// ---------------------------------------------------------
// P1 → P2 Response
// ---------------------------------------------------------

export interface P1ToP2Response {
  command_id: string;

  command_type: P2CommandType;

  success: boolean;

  event_state?: P1EventState;

  validation?: P1ValidationResult;

  simulation?: P1SimulationResult;

  error?: string;
}

// ---------------------------------------------------------
// Contract Validation Result
// ---------------------------------------------------------

export interface ContractValidationResult {
  valid: boolean;

  errors: string[];

  warnings: string[];
}

// ---------------------------------------------------------
// Validate P2 → P1 Command
// ---------------------------------------------------------

export function validateP2Command(
  command: P2ToP1Command,
): ContractValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!command.command_id.trim()) {
    errors.push("command_id is required");
  }

  if (!command.event_id.trim()) {
    errors.push("event_id is required");
  }

  if (!command.command_type) {
    errors.push("command_type is required");
  }

  /**
   * Strategy commands require a strategy ID.
   */
  if (
    command.command_type === "VALIDATE_STRATEGY" ||
    command.command_type === "SIMULATE_STRATEGY"
  ) {
    if (!command.strategy_id?.trim()) {
      errors.push(
        "strategy_id is required for strategy commands",
      );
    }

    if (!command.parameters) {
      warnings.push(
        "No strategy parameters were provided.",
      );
    }
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings,
  };
}

// ---------------------------------------------------------
// Create P2 → P1 Command
// ---------------------------------------------------------

export function createP2Command(
  commandType: P2CommandType,
  eventId: string,
  commandId: string,
  strategyId?: string,
  parameters?: Record<string, unknown>,
  reason?: string,
): P2ToP1Command {
  return {
    command_id: commandId,
    command_type: commandType,
    event_id: eventId,
    strategy_id: strategyId,
    parameters,
    reason,
  };
}

// ---------------------------------------------------------
// Check Whether P1 Response Is Successful
// ---------------------------------------------------------

export function isSuccessfulP1Response(
  response: P1ToP2Response,
): boolean {
  return response.success === true;
}

// ---------------------------------------------------------
// Extract Simulation Results
// ---------------------------------------------------------

export function getSimulationResults(
  response: P1ToP2Response,
): Record<string, unknown> | undefined {
  if (!response.simulation) {
    return undefined;
  }

  if (!response.simulation.success) {
    return undefined;
  }

  return response.simulation.results;
}