'use client';
import {createContext,useContext,useEffect,useState,useCallback} from 'react';
const EventContext=createContext<any>(null);
export const useEvent=()=>useContext(EventContext);
export default function EventLive({children}:{children:React.ReactNode}){
 const [event,setEvent]=useState<any>(null),[graph,setGraph]=useState<any>({nodes:[],edges:[],routes:[],updates:[]}),[connection,setConnection]=useState('disconnected'),[canEdit,setCanEdit]=useState(false),[error,setError]=useState('');
 const reload=useCallback(async()=>{try{const r=await fetch('/api/event'),j:any=await r.json();if(!r.ok)throw Error(j.error);setEvent(j.event);if(j.event){const r=await fetch(`/api/events/${encodeURIComponent(j.event.id)}/graph`),g:any=await r.json();if(!r.ok)throw Error(g.error);setGraph(g)}else setGraph({nodes:[],edges:[],routes:[],updates:[]});setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{reload();fetch('/api/auth').then(r=>r.json()).then((j:any)=>setCanEdit(['admin','owner'].includes(j.access))).catch(()=>{});window.addEventListener('eventflow:event-changed',reload);return()=>window.removeEventListener('eventflow:event-changed',reload)},[reload]);
 useEffect(()=>{if(!event?.id||!graph.socketUrl){setConnection('disconnected');return}let socket:WebSocket,timer:ReturnType<typeof setTimeout>,stopped=false;const channel=`event:${event.id}:update`;function connect(){setConnection('connecting');try{socket=new WebSocket(graph.socketUrl);socket.onopen=()=>{setConnection('connected');socket.send(JSON.stringify({action:'subscribe',channel}))};socket.onmessage=e=>{try{const message=JSON.parse(e.data);if(message.channel&&message.channel!==channel)return;const p=message.data??message;setGraph((g:any)=>({...g,nodes:g.nodes.map((n:any)=>n.node_id===p.nodeId&&p.visitorsNow!=null?{...n,visitorsNow:p.visitorsNow}:n),routes:Array.isArray(p.updatedRoutes)?p.updatedRoutes:g.routes,updates:p.alertText?[...g.updates,{text:p.alertText,updatedAt:p.updatedAt??null}]:g.updates}))}catch{}};socket.onerror=()=>socket.close();socket.onclose=()=>{setConnection('disconnected');if(!stopped)timer=setTimeout(connect,5000)}}catch{setConnection('disconnected')}}connect();return()=>{stopped=true;clearTimeout(timer);socket?.close()}},[event?.id,graph.socketUrl]);
 return <EventContext.Provider value={{event,graph,connection,canEdit,error,reload}}>{children}</EventContext.Provider>
}
