import {database} from './admin';
import {z} from 'zod';
export async function currentEvent(){const row=await database().prepare("SELECT data FROM active_event WHERE id='active'").first<any>();return row?JSON.parse(row.data):null}
export async function record(kind:string,eventId:string,data:unknown,actor:string,parentId:string|null=null,id=crypto.randomUUID()){await database().prepare('INSERT INTO operation_records (id,event_id,kind,parent_id,data,created_at,actor) VALUES (?,?,?,?,?,?,?)').bind(id,eventId,kind,parentId,JSON.stringify(data),new Date().toISOString(),actor).run();return id}
export async function records(eventId:string){const r=await database().prepare('SELECT * FROM operation_records WHERE event_id=? ORDER BY created_at DESC').bind(eventId).all<any>();return r.results.map(x=>({...x,data:JSON.parse(x.data)}))}
export const metrics=z.array(z.object({label:z.string(),before:z.union([z.string(),z.number()]),after:z.union([z.string(),z.number()]),unit:z.string().optional()}));
export const analysisSchema=z.object({title:z.string(),description:z.string(),risk:z.string(),minutesToOvercrowding:z.number().nonnegative().nullable().optional(),baseline:metrics,strategies:z.array(z.object({id:z.string(),title:z.string(),description:z.string(),benefits:z.array(z.string()),recommended:z.boolean().optional()})).min(1)});
export const simulationSchema=z.object({metrics,crowdReduction:z.number().min(0).max(100).nullable().optional(),residualRisk:z.string(),constraintsPassed:z.boolean(),constraints:z.array(z.string()),directives:z.array(z.object({group:z.enum(['Transportation','Hospitality & Providers','Travelers']),message:z.string(),actions:z.array(z.string()),destination:z.object({lat:z.number().min(-90).max(90),lon:z.number().min(-180).max(180)}).optional()}))});
export const deliverySchema=z.object({updates:z.array(z.object({group:z.enum(['Transportation','Hospitality & Providers','Travelers']),status:z.enum(['queued','sent','failed','live']),message:z.string(),updatedAt:z.string().datetime({offset:true})}))});
